---
- name: "(Setup: All NGINX) Ensure NGINX WAF Policy Directory Exists"
  file:
    path: "{{ nginx_main_upload_dest | default('/etc/nginx/wafpolicy') }}"
    state: directory

- name: "(Setup: All NGINX) Upload NGINX Updated WAF Policy Configuration File"
  copy:
    src: "{{ nginx_main_upload_src | default('conf/nginx.conf') }}"
    dest: "{{ nginx_main_upload_dest | default('/etc/nginx/') }}"
    backup: yes
  notify: "(Handler: All OSs) Reload NGINX"

- name: "(Handler: All OSs) Reload NGINX"
    command: "nginx -s reload"
    changed_when: false