---
- name: Update NAP Config
  hosts: 10.200.1.145
  gather_facts: no

  tasks:
  - name: "Ensure NGINX WAF Policy Directory Exists"
    file:
      path: "{{ nginx_main_upload_dest | default('/etc/nginx/wafpolicy') }}"
      state: directory

  - name: "Upload NGINX Updated WAF Policy - DVWA"
    copy:
      src: "{{ nginx_main_upload_src | default('dvwa-policy-v1.json') }}"
      dest: "{{ nginx_main_upload_dest | default('/etc/nginx/wafpolicy') }}"
      backup: no
      
  - name: "Upload NGINX Updated WAF Policy - Default Policy"
    copy:
      src: "{{ nginx_main_upload_src | default('NginxDefaultPolicy.json') }}"
      dest: "{{ nginx_main_upload_dest | default('/etc/nginx/wafpolicy') }}"
      backup: no
      
  - name: "Upload NGINX Configuration File"
    copy:
      src: "{{ nginx_main_upload_src | default('nginx.conf') }}"
      dest: "{{ nginx_main_upload_dest | default('/etc/nginx') }}"
      backup: no

  - name: "Reload NGINX"
    command: "/usr/sbin/nginx -s reload"
    
