---
- name: Update NAP Config
  hosts: nginx

  tasks:
  - name: "Ensure NGINX WAF Policy Directory Exists"
    file:
      path: "{{ nginx_main_upload_dest | default('/etc/nginx/wafpolicy') }}"
      state: directory

  - name: "Upload NGINX Updated WAF Policy Configuration File"
    copy:
      src: "{{ nginx_main_upload_src | default('dvwa-policy-v1.json') }}"
      dest: "{{ nginx_main_upload_dest | default('/etc/nginx/wafpolicy') }}"
      backup: yes

  - name: "Reload NGINX"
    command: "nginx -s reload"
    become: yes
    become_user: mholland
    become_method: sudo
    
